### ISSUE TITLE
icinga.icinga2 was NOT installed successfully: - sorry, icinga.icinga2 was not found on https://galaxy.ansible.com.

### ISSUE THREAD

**Issue by evollution** [Icinga/ansible-icinga2#32]
Hello,
when i try to install icinga2 via ansible-galaxy i get the following error :+1:
icinga.icinga2 was not found on https://galaxy.ansible.com.

**Comment by RossBarnie** [comment]
Duplicate of https://github.com/Icinga/ansible-icinga2/issues/29. This role is still in development and not available on Galaxy yet.
