### ISSUE TITLE
Future of this project; Refactoring of this role

### ISSUE THREAD

**Issue by flokoe** [Icinga/ansible-icinga2#48]
Hi,

over the past few months, this repository got slowly abandoned, therefore, I had a [talk with Feu in the forum](https://community.icinga.com/t/future-of-the-ansible-role-for-icinga2-is-there-a-plan-and-what-can-we-expect/5168) and later with @bobapple to see how I can help.

To revive this repository I would like to make a few changes or rather a basic refactoring of this repository.

This includes the following steps:

1. Housekeeping (clean up repo, remove unused files, update information/documentation)
2. Rework testing setup
3. See if refactoring of existing functionality is necessary
4. Introduce new branching strategy (just add a devel branch; the master/main branch should only contain the latest working, tagged version)
6. Start adding new features

I hope we can revive this repository and get this Ansible role working again :)

Best regards
Florian

**Comment by aflatto** [comment]
Hi Florian 

The help will be welcome and much appreciated.

I'll gladly review any commit you will push.

Regards

**Comment by rndmh3ro** [comment]
A suggestion: you could convert this role to a collection. Then you could have several roles in the collection that install and configure for example icinga2, icinga web, icinga director...

Aside: We created a collection to manage the director via ansible: https://github.com/T-Systems-MMS/ansible-collection-icinga-director

Maybe in the future this could belong together?

**Comment by flokoe** [comment]
Hey @rndmh3ro,

thank you for your input!

Collections sound interesting, but to be honest I have no experience with them and had no time to look at them in detail yet.

I have seen the role and I have to admit your solution is very interesting!  
As I talked with Blerim (@bobapple) he said that a big part of the Icinga community uses config files, so I guess we still want to support the traditional way of configuration with config files.

But I would be glad if we can join our efforts!

**Comment by jhuebner79** [comment]
@flokoe I've seen this talk in February, maybe it can help you understand collections: https://fosdem.org/2020/schedule/event/ansible_collections/

**Comment by rndmh3ro** [comment]
If you'd rather read than listen, the ansible docs are good:

* https://docs.ansible.com/ansible/latest/user_guide/collections_using.html
* https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#developing-collections

I can help with setting up a collection.
