### ISSUE TITLE
SLES Support

### ISSUE THREAD

**Issue by dh-roland** [Icinga/ansible-icinga2#52]
In the ansible_collections/icinga/icinga the role for SLES is missing. Is its possible to add SLES support?

user@host:~/.ansible/collections/ansible_collections/icinga/icinga/roles/icinga2/tasks$ ls
configure.yml  features  features.yml  install.yml  install_on_Debian.yml  install_on_RedHat.yml  main.yml  objects.yml  service.yml

**Comment by lbetz** [comment]
Hi,

thx for the issue, but this is the wrong project. Please reopen the issue in
https://github.com/Icinga/ansible-collection-icinga/issues, again.
